### ISSUE TITLE
Design schemas

### ISSUE THREAD

**Issue by SamPenrose** [mozilla-services/data-pipeline#146]
I did a quick pass with JSON Schema here:

https://github.com/SamPenrose/data-pipeline/tree/v4-baseset-schema

It contains very simple schemas for the v4 ping base set and for the crash report summary:

https://github.com/mozilla-services/data-pipeline/commit/8db43c2858d281eb97cc3dec51e218c518816715#diff-7f43c97b668e167199226f466d0ee101R45

Plus unit tests in Python. Everything here is up for grabs except the idea that we should have a machine parseable schema format that different Pipeline components can read when working with common data structures.

Where should we take this?

**Comment by mreid-moz** [comment]
Sam, can you try making an [Avro](http://avro.apache.org/docs/current/) version of this schema? Then we can use it for generating some test data sets and storing in parquet format.

**Comment by mreid-moz** [comment]
We now have a repo over at https://github.com/mozilla-services/mozilla-pipeline-schemas built from Sam's initial work (which is awesome, and thanks again).

@SamPenrose should we close this issue?

**Comment by SamPenrose** [comment]
Definitely, thanks so much for seeing this through.
