### ISSUE TITLE
Fix the failing `kafkaconsumergroup` test

### ISSUE THREAD

**Issue by mreid-moz** [mozilla-services/data-pipeline#152]
The most recent build failed with the following message:

```
kafka_consumer_group_input_test.go:52: Expected: zk: could not connect to a server, received: too many colons in address ::
```

It doesn't seem terribly interesting what the specific error message says - is it sufficient to check that an error was returned? Or can we adjust the bogus ZooKeeper connection string to cause a more predictable error string?

**Comment by whd** [comment]
We can simply check for an error, but perhaps also we should pin the consumer group revision like we do with everything else. I will see to this.
