### ISSUE TITLE
Consider factoring out the retry logic

### ISSUE THREAD

**Issue by mreid-moz** [mozilla-services/data-pipeline#164]
Consider moving the "retry once" logic from `hindsight/io_modules/derived_stream.lua` into the `insert_file` and `copy_file` functions, rather than repeating retry logic inside process_message and timer_event.

**Comment by trink** [comment]
both process_message and timer_event use `*_file` and utilize different retry strategies (so moving it to the function wouldn't work well)

**Comment by mreid-moz** [comment]
Considered, rejected.  :)
