### ISSUE TITLE
Handle GeoIP/X-Forwarded-For properly when teeing traffic

### ISSUE THREAD

**Issue by whd** [mozilla-services/data-pipeline#17]
The `RemoteAddr` field as set by `HttpListenInput` will always be the frontend ELB of the edge ASG, so we should never consider it when doing a GeoIP lookup. `X-Forwarded-For` should (in ordinary cases) have the client IP address.

However, once we set up the tee, `X-Forwarded-For` is going to be passed from the Tee Server to the new pipeline and old telemetry ELBs as `CLIENT_IP`, and the respective new and old ELBs will set `X-Forwarded-For` to `CLIENT_IP, TEE_ELB_IP` before sending the request to a backend server. Therefore, for clients that are not misbehaving, we need to parse `X-Forwarded-For` as a CSV and use the first entry for the GeoIP lookup. (I should also note that depending on how old telemetry processes IP addresses there could be similar problems introduced by the tee).

In fact the value of `X-Forwarded-For` is not standardized and can at least partially be arbitrarily set by the client. Because the client can supply a list of `X-Forwarded-For`s itself I suppose the correct way to handle the parsing is:
1. Parse `X-Forwarded-For` as a CSV (with spaces permitted) and drop the last entry (which we know will always be `TEE_ELB_IP`)
2. Try a GeoIP lookup on each remaining entry in order

However, dropping the last entry as described above is somewhat problematic in that turning off the tee will require a code change (or config option) to get the original intended behavior.

**Comment by mreid-moz** [comment]
If we change the code to parse X-Forwarded-For as a comma-separated list, and accept the first valid one (starting from the left), that should work whether there are extra ones at the end or not (since the left-most is always closest to the client).  Then we don't have to change anything when we remove the Tee server. The short-circuit on valid IP will take care of that.

**Comment by whd** [comment]
I thought the intent of the current code is to look up the client-provided "X-Forwarded-For", and if that fails, look up the client's "X-Real-IP". Choosing the leftmost valid IP would only ever look up one IP, but that seems acceptable to me.

**Comment by mreid-moz** [comment]
Right, the current code tries to look up XFF, then falls back to the actual request IP. That way it works whether it's behind a load balancer or not (as long as the LB adds the XFF header as expected).
